##################################################  
################  COMMON ENTITIES  ###############  
##################################################  

###############  input_boolean:  #################  
input_boolean:
  garagesd_lock_notifications:
    name: "Lock Notifications"
  garagesd_dooraccess_notifications:
    name: "Door Notifications"
  garagesd_garageacess_notifications:
    name: "Garage Notifications"
  garagesd_reset_lock:
    name: "garagesd reset lock"

############## binary_sensor:  ####################  
binary_sensor:
- platform: template
  sensors:
  
    sensornamedelsd_access_control_frontdoordelsd:
      value_template: "{{ is_state('sensor.sensornamedelsd_access_control_frontdoordelsd', '22') }}"
      friendly_name: "frontdoordelsd"
      device_class: door

    sensornamedelsd_burglar_frontdoordelsd:
      value_template: "{{ is_state('sensor.sensornamedelsd_burglar_frontdoordelsd', '3') }}"
      friendly_name: "frontdoordelsd Sensor Tamper"
      device_class: safety

###################  sensor:  ####################  
sensor:

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'

- platform: template
  sensors:

    garagesd_statusreport:
      friendly_name: 'garagesd Status Report'
      value_template: >
          {% set number = states('sensor.schlage_allegion_be469zp_connect_smart_deadbolt_alarm_level_garagesd') %}
          {% set alarm_type_value = states('sensor.schlage_allegion_be469zp_connect_smart_deadbolt_alarm_type_garagesd') %}

          {% if ((as_timestamp(now())-as_timestamp(states.lock.schlage_allegion_be469zp_connect_smart_deadbolt_locked_garagesd.last_changed)) < 15 and (as_timestamp(now())-as_timestamp(states.sensor.schlage_allegion_be469zp_connect_smart_deadbolt_alarm_type_garagesd.last_changed)) > 15) %}

          {%    if (states.lock.schlage_allegion_be469zp_connect_smart_deadbolt_locked_garagesd.state) == 'locked' %}
          {%       set alarm_type_value = '24' %}
          {%    elif (states.lock.schlage_allegion_be469zp_connect_smart_deadbolt_locked_garagesd.state) == 'unlocked' %}
          {%       set alarm_type_value = '25' %}
          {%    endif %}

          {% endif %}
          
          {% set alarm_type_general_actions = {
            '0':'No Status Reported',          
            '9':'Lock Jammed',
            '17':'Keypad Lock Jammed',
            '21':'Manual Lock',
            '22':'Manual Unlock',
            '23':'HA Lock Jammed',
            '24':'HA Lock',
            '25':'HA Unlock',
            '26':'Auto Lock Jammed',
            '27':'Auto Lock',
            '32':'All Codes Deleted',
            '161':'Bad Code Entered',
            '167':'Battery Low',
            '168':'Battery Critical',
            '169':'Battery Too Low To Operate Lock' } %}
          {% set alarm_type_lock_actions = {
            '18':'Keypad Lock',
            '19':'Keypad Unlock',
            '162':'Lock Code Attempt Outside of Schedule' } %}
          {% set alarm_type_code_actions = {
            '33':'Code Deleted',
            '112':'Code Changed',
            '113':'Duplicate Code' } %}
          {% if alarm_type_value in alarm_type_code_actions %}
            {{alarm_type_value}};{{ alarm_type_code_actions[alarm_type_value] }};{{number}}
          {% elif alarm_type_value in alarm_type_lock_actions  %}
            {{alarm_type_value}};{{ alarm_type_lock_actions[alarm_type_value] }};{{number}}
          {% elif alarm_type_value in alarm_type_general_actions %}
            {{alarm_type_value}};{{ alarm_type_general_actions[alarm_type_value] }}
          {% else %}
            {{-1}};Unknown Alarm Type Value {{ states('sensor.schlage_allegion_be469zp_connect_smart_deadbolt_alarm_type_garagesd') }}
          {% endif %}

###################  script    :  ####################
script:
  garagesd_reset_lock:
    sequence:
      - service: script.garagesd_manual_notify
        data_template:   
          title: "reset"
          message: "garagesd"

  garagesd_conditional_notify:
    sequence:
      - condition: template
        value_template: >-
          {% set inputbool = boolean %}
          {% if states(inputbool) == 'on'%}
            true
          {% else %}
            false
          {% endif %}
      - service: script.garagesd_manual_notify
        data_template:   
          title: "{{title}}"
          message: "{{message}}"

  garagesd_manual_notify:
    sequence:
      - service: notify.my_devices
        data_template:   
          title: "{{title}}"
          message: "{{message}}"
    
######################################################  

###################  automation:  ####################  
automation:

    - alias: GarageSD Notifications
      trigger:
        platform: state
        entity_id: sensor.garagesd_statusreport
      condition:
        - condition: state
          entity_id: 'binary_sensor.allow_automation'
          state: 'on' 
        - condition: template
          value_template: >-
            {% set report = states.sensor.garagesd_statusreport.state %}
            {% set a = report.split(';') %}
            {% if (a|length) != 3 or (a[2] == "0") %} 
              {{ true }}
            {% else %}
              {{ true }}
            {% endif %}
      action:
        - service: script.conditional_notify
          data_template:
            boolean: input_boolean.garagesd_lock_notifications
            title: "Sensor Status Report"
            message: >-
              {% set report = states.sensor.garagesd_statusreport.state %}
              {% set a = report.split(';') %}
              {% set msg = "ID:" + a[0] + " MSG:" + a[1] %}
              {% if (a|length) == 3 %}
              {%   set msg = msg + " SLOT:" + a[2] %}
              {% endif %}
              {{ a[1] }}
    
    - alias: GarageSD User Notifications
      trigger:
        platform: state
        entity_id: sensor.garagesd_statusreport
      condition:
        - condition: state
          entity_id: 'binary_sensor.allow_automation'
          state: 'on' 
        - condition: template
          value_template: >-
            {% set report = states.sensor.garagesd_statusreport.state %}
            {% set a = report.split(';') %}
            {% if (a|length) == 3 and (a[2] | int > 0) %} 
              {{ true }}
            {% else %}
              {{ false }}
            {% endif %}
        - condition: template
          value_template: >-
            {% set report = states.sensor.garagesd_statusreport.state %}
            {% set a = report.split(';') %}
            {% set entity_id = 'notify_garagesd_' + a[2] %}
            {% set notify = states['input_boolean'][entity_id].state %}
            {{ notify == "on" }}
      action:
        - service: script.manual_notify
          data_template:
            title: >- 
              {% set report = states.sensor.garagesd_statusreport.state %}
              {% set a = report.split(';') %}
              {{ a[1] }}
            message: >-
              {% set report = states.sensor.garagesd_statusreport.state %}
              {% set a = report.split(';') %}
              {% set entity_id = 'input_text.garagesd_name_' + a[2] %}
              {% set user = states(entity_id) %}
              {{ user }}

###############################
    - alias: frontdoordelsd Sensor Close
      condition:
        - condition: state
          entity_id: 'binary_sensor.allow_automation'
          state: 'on' 
      trigger:
        entity_id: binary_sensor.sensornamedelsd_access_control_frontdoordelsd
        platform: state
        to: 'off'
      action:
        - service: script.conditional_notify
          data_template:
            boolean: input_boolean.garagesd_dooraccess_notifications
            title: "frontdoordelsd"    
            message: "Closed"

    - alias: frontdoordelsd Sensor Opened
      condition:
        - condition: state
          entity_id: 'binary_sensor.allow_automation'
          state: 'on' 
      trigger:
        entity_id: binary_sensor.sensornamedelsd_access_control_frontdoordelsd
        platform: state
        to: 'on'
      action:
        - service: script.conditional_notify
          data_template:
            boolean: input_boolean.garagesd_dooraccess_notifications
            title: "frontdoordelsd"    
            message: "Opened"
    
    - alias: GarageSD Add Code
      condition:
        - condition: state
          entity_id: 'binary_sensor.allow_automation'
          state: 'on' 
      trigger:
        entity_id: binary_sensor.active_garagesd_1, binary_sensor.active_garagesd_2, binary_sensor.active_garagesd_3, binary_sensor.active_garagesd_4, binary_sensor.active_garagesd_5, binary_sensor.active_garagesd_6
        platform: state
        to: 'on'
      action:
        - service: lock.set_usercode
          data_template:
            node_id: >- 
                {{states.lock.schlage_allegion_be469zp_connect_smart_deadbolt_locked_garagesd.attributes.node_id}}
            code_slot: >-
                {% set object_id = trigger.to_state.object_id %}
                {% set index = 17 %}
                {% set code_slot = object_id[index:] %}
                {{ code_slot  }}
            usercode: >-
                {% set object_id = trigger.to_state.object_id %}
                {% set index = 17 %}
                {% set code_slot = object_id[index:] %}    
                {% set codetext = 'garagesd_pin_' + code_slot | string %}
                {% set code = states['input_text'][codetext].state %}
                {{ code | string }}

    - alias: GarageSD Update Code
      trigger:
        entity_id: input_text.garagesd_pin_1, input_text.garagesd_pin_2, input_text.garagesd_pin_3, input_text.garagesd_pin_4, input_text.garagesd_pin_5, input_text.garagesd_pin_6
        platform: state
      condition:
        - condition: state
          entity_id: 'binary_sensor.allow_automation'
          state: 'on' 
        - condition: template
          value_template: >-
            {% set object_id = trigger.to_state.object_id %}
            {% set index = 14 %}
            {% set code_slot = object_id[index:] %}
            {% set b = 'input_boolean.enabled_garagesd_' + code_slot | string %}
            {{ is_state(b, 'on') and (trigger.from_state.state != trigger.to_state.state)}}
      action:
        - service: persistent_notification.create
          data_template:
            title: "garagesd LOCK MANAGER"
            message: >-
              {% set object_id = trigger.to_state.object_id %}
              {% set index = 14 %}
              {% set code_slot = object_id[index:] %}
              {{ 'You changed the PIN for code  ' + code_slot | string + '. Please enable it in order to make it active.'}}
        - service: input_boolean.turn_off
          data_template:
            entity_id: >-
              {% set object_id = trigger.to_state.object_id %}
              {% set index = 14 %}
              {% set code_slot = object_id[index:] %}
              {{ 'input_boolean.enabled_garagesd_' + code_slot | string }}

    - alias: Reset GarageSD
      condition:
        - condition: state
          entity_id: 'binary_sensor.allow_automation'
          state: 'on' 
      trigger:
        entity_id: input_boolean.garagesd_reset_lock
        platform: state
        from: 'off'
        to: 'on'
      action:
        - service: script.garagesd_reset_lock
        - service: input_boolean.turn_off
          entity_id: input_boolean.garagesd_reset_lock
    
    - alias: GarageSD Clear Code
      condition:
        - condition: state
          entity_id: 'binary_sensor.allow_automation'
          state: 'on' 
      trigger:
        entity_id: binary_sensor.active_garagesd_1, binary_sensor.active_garagesd_2, binary_sensor.active_garagesd_3, binary_sensor.active_garagesd_4, binary_sensor.active_garagesd_5, binary_sensor.active_garagesd_6
        platform: state
        to: 'off'
      action:
        # - service: lock.clear_usercode
        #   data_template:
        #     node_id: >- 
        #         {{states.lock.schlage_allegion_be469zp_connect_smart_deadbolt_locked_garagesd.attributes.node_id}}
        #     code_slot: >-
        #         {% set object_id = trigger.to_state.object_id %}
        #         {% set index = 17 %}
        #         {% set code_slot = object_id[inex:] %}
        #         {{ code_slot  }}
        - service: lock.set_usercode
          data_template:
            node_id: >- 
              {{states.lock.schlage_allegion_be469zp_connect_smart_deadbolt_locked_garagesd.attributes.node_id}}
            code_slot: >-
              {% set index = 17 %}
              {% set object_id = trigger.to_state.object_id %}
              {% set code_slot = object_id[index:] %}
              {{ code_slot  }}
            usercode: >-
              {{ range(1000, 9999) | random | int }}

    - alias: GarageSD Decrement Access Count
      trigger:
        platform: state
        entity_id: sensor.garagesd_statusreport
      condition:
        - condition: state
          entity_id: 'binary_sensor.allow_automation'
          state: 'on' 
        - condition: template
          value_template: >-
            {% set report = states.sensor.garagesd_statusreport.state %}
            {% set a = report.split(';') %}
            {% if (a|length) == 3 and (a[2] | int > 0) %} 
               {{ (a[0] | int == 19) }}
            {% else %}
              {{ false }}
            {% endif %}
      action:
        - service: input_number.decrement
          data_template:
            entity_id: >-
              {% set report = states.sensor.garagesd_statusreport.state %}
              {% set a = report.split(';') %}
              {{ 'input_number.accesscount_garagesd_' + a[2] }}
