
############  input_number:  #####################  
input_number:
  accesscount_garagesd_2:
    name: Access Count
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "Openings Left"

#################  input_datetime:  ##############  
input_datetime:
  end_date_garagesd_2:
    name: 'End'
    has_time: false
    has_date: true
  start_date_garagesd_2:
    name: 'Start'
    has_time: false
    has_date: true

  sun_start_date_garagesd_2:
    name: 'Start'
    has_time: true
    has_date: false
  sun_end_date_garagesd_2:
    name: 'End'
    has_time: true
    has_date: false

  mon_start_date_garagesd_2:
    name: 'Start'
    has_time: true
    has_date: false
  mon_end_date_garagesd_2:
    name: 'End'
    has_time: true
    has_date: false

  tue_start_date_garagesd_2:
    name: 'Start'
    has_time: true
    has_date: false
  tue_end_date_garagesd_2:
    name: 'End'
    has_time: true
    has_date: false

  wed_start_date_garagesd_2:
    name: 'Start'
    has_time: true
    has_date: false
  wed_end_date_garagesd_2:
    name: 'End'
    has_time: true
    has_date: false

  thu_start_date_garagesd_2:
    name: 'Start'
    has_time: true
    has_date: false
  thu_end_date_garagesd_2:
    name: 'End'
    has_time: true
    has_date: false

  fri_start_date_garagesd_2:
    name: 'Start'
    has_time: true
    has_date: false
  fri_end_date_garagesd_2:
    name: 'End'
    has_time: true
    has_date: false

  sat_start_date_garagesd_2:
    name: 'Start'
    has_time: true
    has_date: false
  sat_end_date_garagesd_2:
    name: 'End'
    has_time: true
    has_date: false


####################  input_text:  ###############  
input_text:
  garagesd_name_2:
    name: 'Name'
  garagesd_pin_2:
    name: 'PIN'

#################  input_boolean: ################  
input_boolean:
  notify_garagesd_2:
    name: 'Notifications'
  daterange_garagesd_2:
    name: 'Use Date Range'
  smtwtfs_garagesd_2:
    name: 'Use SMTWTFS'
  enabled_garagesd_2:
    name: 'Enabled'
  accesslimit_garagesd_2:
    name: 'Limit Access Count'
    initial: off
  reset_advanced_garagesd_2:
    name: 'Reset Advanaced Options'
    initial: off

  sun_garagesd_2:
    name: 'Sunday'
    initial: on

  mon_garagesd_2:
    name: 'Monday'
    initial: on

  tue_garagesd_2:
    name: 'Tuesday'
    initial: on

  wed_garagesd_2:
    name: 'Wednesday'
    initial: on

  thu_garagesd_2:
    name: 'Thursday'
    initial: on

  fri_garagesd_2:
    name: 'Friday'
    initial: on

  sat_garagesd_2:
    name: 'Saturday'
    initial: on

################  automation: #################  
automation:

- alias: reset_advanced_GarageSD_2
  trigger:
    entity_id: input_boolean.reset_advanced_garagesd_2
    platform: state
    to: 'on'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.accesscount_garagesd_2
        value: "0"
      
    - service: input_datetime.set_datetime
      entity_id: input_datetime.sun_start_date_garagesd_2
      data_template:
        time: >
          {{  (("00:00")  | timestamp_custom("%H:%M"))  }}      
    - service: input_datetime.set_datetime
      entity_id: input_datetime.sun_end_date_garagesd_2
      data_template:
        time: >
          {{  (("00:00")  | timestamp_custom("%H:%M"))  }}      
    - service: input_datetime.set_datetime
      entity_id: input_datetime.mon_start_date_garagesd_2
      data_template:
        time: >
          {{  (("00:00")  | timestamp_custom("%H:%M"))  }}      
    - service: input_datetime.set_datetime
      entity_id: input_datetime.mon_end_date_garagesd_2
      data_template:
        time: >
          {{  (("00:00")  | timestamp_custom("%H:%M"))  }}      
    - service: input_datetime.set_datetime
      entity_id: input_datetime.tue_start_date_garagesd_2
      data_template:
        time: >
          {{  (("00:00")  | timestamp_custom("%H:%M"))  }}      
    - service: input_datetime.set_datetime
      entity_id: input_datetime.tue_end_date_garagesd_2
      data_template:
        time: >
          {{  (("00:00")  | timestamp_custom("%H:%M"))  }}      
    - service: input_datetime.set_datetime
      entity_id: input_datetime.wed_start_date_garagesd_2
      data_template:
        time: >
          {{  (("00:00")  | timestamp_custom("%H:%M"))  }}      
    - service: input_datetime.set_datetime
      entity_id: input_datetime.wed_end_date_garagesd_2
      data_template:
        time: >
          {{  (("00:00")  | timestamp_custom("%H:%M"))  }}      
    - service: input_datetime.set_datetime
      entity_id: input_datetime.thu_start_date_garagesd_2
      data_template:
        time: >
          {{  (("00:00")  | timestamp_custom("%H:%M"))  }}      
    - service: input_datetime.set_datetime
      entity_id: input_datetime.thu_end_date_garagesd_2
      data_template:
        time: >
          {{  (("00:00")  | timestamp_custom("%H:%M"))  }}      
    - service: input_datetime.set_datetime
      entity_id: input_datetime.fri_start_date_garagesd_2
      data_template:
        time: >
          {{  (("00:00")  | timestamp_custom("%H:%M"))  }}      
    - service: input_datetime.set_datetime
      entity_id: input_datetime.fri_end_date_garagesd_2
      data_template:
        time: >
          {{  (("00:00")  | timestamp_custom("%H:%M"))  }}      
    - service: input_datetime.set_datetime
      entity_id: input_datetime.sat_start_date_garagesd_2
      data_template:
        time: >
          {{  (("00:00")  | timestamp_custom("%H:%M"))  }}      
    - service: input_datetime.set_datetime
      entity_id: input_datetime.sat_end_date_garagesd_2
      data_template:
        time: >
          {{  (("00:00")  | timestamp_custom("%H:%M"))  }}      
          
    - service: input_datetime.set_datetime
      entity_id: input_datetime.start_date_garagesd_2
      data_template:
        date: >
          {{  (("1980-01-01")  | timestamp_custom("%Y %m %d"))  }}      
          
    - service: input_datetime.set_datetime
      entity_id: input_datetime.end_date_garagesd_2
      data_template:
        date: >
          {{  (("1980-01-01")  | timestamp_custom("%Y %m %d"))  }}      

    - service: input_boolean.turn_off
      entity_id: input_boolean.daterange_garagesd_2

    - service: input_boolean.turn_off
      entity_id: input_boolean.accesslimit_garagesd_2
      
    - service: input_boolean.turn_off
      entity_id: input_boolean.reset_advanced_garagesd_2
      
    - service: input_boolean.turn_on
      entity_id: input_boolean.sun_garagesd_2
      
    - service: input_boolean.turn_on
      entity_id: input_boolean.mon_garagesd_2
      
    - service: input_boolean.turn_on
      entity_id: input_boolean.tue_garagesd_2
      
    - service: input_boolean.turn_on
      entity_id: input_boolean.wed_garagesd_2
      
    - service: input_boolean.turn_on
      entity_id: input_boolean.thu_garagesd_2
      
    - service: input_boolean.turn_on
      entity_id: input_boolean.fri_garagesd_2
      
    - service: input_boolean.turn_on
      entity_id: input_boolean.sat_garagesd_2
      
################  binary_sensor: #################  
binary_sensor:

- platform: template
  sensors:

    enabled_garagesd_2:
      value_template: "{{ is_state('input_boolean.enabled_garagesd_2', 'on') }}"

    daterange_garagesd_2:
      value_template: "{{ (is_state('input_boolean.daterange_garagesd_2', 'off') or ((states.input_datetime.start_date_garagesd_2.attributes.timestamp| int | timestamp_custom('%Y%m%d', False)|int)|string <= now().strftime('%Y%m%d')) and (states.input_datetime.end_date_garagesd_2.attributes.timestamp| int | timestamp_custom('%Y%m%d', False)|int)|string >=  now().strftime('%Y%m%d'))}}"

    sun_garagesd_2:
      entity_id:
        - sensor.time
        - input_datetime.sun_start_date_garagesd_2
        - input_datetime.sun_end_date_garagesd_2
      value_template: "{{ ((is_state('input_boolean.sun_garagesd_2', 'on'))) and (strptime(states('sensor.date'), '%Y-%m-%d').strftime('%A') == 'Sunday') and ((states.input_datetime.sun_start_date_garagesd_2.state  == states.input_datetime.sun_end_date_garagesd_2.state) or ((states('sensor.time') >= states('input_datetime.sun_start_date_garagesd_2')[0:5]) and (states('sensor.time') <= states('input_datetime.sun_end_date_garagesd_2')[0:5]))) }}"

    mon_garagesd_2:
      entity_id:
        - sensor.time
        - input_datetime.mon_start_date_garagesd_2
        - input_datetime.mon_end_date_garagesd_2
      value_template: "{{ ((is_state('input_boolean.mon_garagesd_2', 'on'))) and (strptime(states('sensor.date'), '%Y-%m-%d').strftime('%A') == 'Monday') and ((states.input_datetime.mon_start_date_garagesd_2.state  == states.input_datetime.mon_end_date_garagesd_2.state) or ((states('sensor.time') >= states('input_datetime.mon_start_date_garagesd_2')[0:5]) and (states('sensor.time') <= states('input_datetime.mon_end_date_garagesd_2')[0:5]))) }}"

    tue_garagesd_2:
      entity_id:
        - sensor.time
        - input_datetime.tue_start_date_garagesd_2
        - input_datetime.tue_end_date_garagesd_2
      value_template: "{{ ((is_state('input_boolean.tue_garagesd_2', 'on'))) and (strptime(states('sensor.date'), '%Y-%m-%d').strftime('%A') == 'Tuesday') and ((states.input_datetime.tue_start_date_garagesd_2.state  == states.input_datetime.tue_end_date_garagesd_2.state) or ((states('sensor.time') >= states('input_datetime.tue_start_date_garagesd_2')[0:5]) and (states('sensor.time') <= states('input_datetime.tue_end_date_garagesd_2')[0:5]))) }}"

    wed_garagesd_2:
      entity_id:
        - sensor.time
        - input_datetime.wed_start_date_garagesd_2
        - input_datetime.wed_end_date_garagesd_2
      value_template: "{{ ((is_state('input_boolean.wed_garagesd_2', 'on'))) and (strptime(states('sensor.date'), '%Y-%m-%d').strftime('%A') == 'Wednesday') and ((states.input_datetime.wed_start_date_garagesd_2.state  == states.input_datetime.wed_end_date_garagesd_2.state) or ((states('sensor.time') >= states('input_datetime.wed_start_date_garagesd_2')[0:5]) and (states('sensor.time') <= states('input_datetime.wed_end_date_garagesd_2')[0:5]))) }}"

    thu_garagesd_2:
      entity_id:
        - sensor.time
        - input_datetime.thu_start_date_garagesd_2
        - input_datetime.thu_end_date_garagesd_2
      value_template: "{{ ((is_state('input_boolean.thu_garagesd_2', 'on'))) and (strptime(states('sensor.date'), '%Y-%m-%d').strftime('%A') == 'Thursday') and ((states.input_datetime.thu_start_date_garagesd_2.state  == states.input_datetime.thu_end_date_garagesd_2.state) or ((states('sensor.time') >= states('input_datetime.thu_start_date_garagesd_2')[0:5]) and (states('sensor.time') <= states('input_datetime.thu_end_date_garagesd_2')[0:5]))) }}"

    fri_garagesd_2:
      entity_id:
        - sensor.time
        - input_datetime.fri_start_date_garagesd_2
        - input_datetime.fri_end_date_garagesd_2
      value_template: "{{ ((is_state('input_boolean.fri_garagesd_2', 'on'))) and (strptime(states('sensor.date'), '%Y-%m-%d').strftime('%A') == 'Friday') and ((states.input_datetime.fri_start_date_garagesd_2.state  == states.input_datetime.fri_end_date_garagesd_2.state) or ((states('sensor.time') >= states('input_datetime.fri_start_date_garagesd_2')[0:5]) and (states('sensor.time') <= states('input_datetime.fri_end_date_garagesd_2')[0:5]))) }}"

    sat_garagesd_2:
      entity_id:
        - sensor.time
        - input_datetime.sat_start_date_garagesd_2
        - input_datetime.sat_end_date_garagesd_2
      value_template: "{{ ((is_state('input_boolean.sat_garagesd_2', 'on'))) and (strptime(states('sensor.date'), '%Y-%m-%d').strftime('%A') == 'Saturday') and ((states.input_datetime.sat_start_date_garagesd_2.state  == states.input_datetime.sat_end_date_garagesd_2.state) or ((states('sensor.time') >= states('input_datetime.sat_start_date_garagesd_2')[0:5]) and (states('sensor.time') <= states('input_datetime.sat_end_date_garagesd_2')[0:5]))) }}"


    smtwtfs_garagesd_2:
      friendly_name: "Status"
      value_template: >-
         {{
            is_state('binary_sensor.sun_garagesd_2', 'on')  or  
            is_state('binary_sensor.mon_garagesd_2', 'on')  or  
            is_state('binary_sensor.tue_garagesd_2', 'on')  or  
            is_state('binary_sensor.wed_garagesd_2', 'on')  or  
            is_state('binary_sensor.thu_garagesd_2', 'on')  or  
            is_state('binary_sensor.fri_garagesd_2', 'on')  or  
            is_state('binary_sensor.sat_garagesd_2', 'on')   
         }}

    
    access_count_garagesd_2:
      friendly_name: "Access Count"
      value_template: >-
         {{
            (is_state('input_boolean.accesslimit_garagesd_2', 'off'))  or  
            (states.input_number.accesscount_garagesd_2.state | int > 0)
         }}


    active_garagesd_2:
      friendly_name: "Status"
      value_template: >-
         {{
            is_state('binary_sensor.enabled_garagesd_2', 'on')  and  
            is_state('binary_sensor.access_count_garagesd_2', 'on')  and  
            is_state('binary_sensor.daterange_garagesd_2', 'on') and
            is_state('binary_sensor.smtwtfs_garagesd_2', 'on')  
         }}
      device_class: connectivity


###################  sensor:  ####################  

